### ISSUE TITLE
User does not have LastSharingCheck property in profile causing error

### ISSUE THREAD

**Issue by extern-hartung-nikolaus** [sassoftware/sas-portal-app#35]
The issue is that - for some reason - this user does not have the LastSharingCheck property in their profile.  
Please adjust code to handle this case.

ERROR: The DATETIME value &startdt. must have the format ddmmmyyyy:hh:mm:ss.

[debug_anyuserid@ALLIANZDE.ROOTDOM.NET_getIndex_sla999999.log](https://github.com/user-attachments/files/16348640/debug_anyuserid%40ALLIANZDE.ROOTDOM.NET_getIndex_sla999999.log)

**Comment by gh4nh** [comment]
fixed with commit https://github.com/sassoftware/sas-portal-app/commit/204565a2af5cd070fc746d12e8ba2e41f5a7417b
