### ISSUE TITLE
SASNavigator portlet sort order by name

### ISSUE THREAD

**Issue by gh4nh** [sassoftware/sas-portal-app#51]
Customer ask to change the sort order of folder and files in SPA Navigator portlet to be ordered by name.
Currently the sort order is by date of the created object (folder or file).

![image](https://github.com/user-attachments/assets/80bd39de-e94c-4189-a6bf-460cde48d6ec)

**Comment by gh4nh** [comment]
In order to resolve this behavior, the file sas\SASEnvironment\Files\portlet\render.sasnavigator.xslt need to be adjusted in the <xsl:template name="listChildren"> in the <xsl:for-each select="$childListParent/*"> with the statement <xsl:sort select="@Name" />

The statement for the sort need to be right below for-each to be valid.

![image](https://github.com/user-attachments/assets/801300af-c90a-4667-aca4-8d2bcff7a782)

**Comment by CraigRubendall** [comment]
I have included this change in my latest push, closing.
