### ISSUE TITLE
Accessing Stored Processes via SAS Navigator Portlet: ERROR when opening Stored Processes with prompts or form fields

### ISSUE THREAD

**Issue by randomsasadmin** [sassoftware/sas-portal-app#52]
We primarily want to use the SAS Navigator Portlet to access Stored Processes. Currently, an error is displayed during execution, as it seems that prompts and form fields are not supported. It might be an idea to pass the parameters in the URL, for example: '/SASStoredProcess/do?_action=form,properties&_program=<program>' (Documentation: https://documentation.sas.com/doc/en/itechcdc/9.4/stpug/n0m6bfw604p33tn1ly7rbrx3ghla.htm#n1b938dmvdgyi0n1oql2tyqirorz).

**Comment by CraigRubendall** [comment]
link changed to include the form and properties option for _action.
